<?php
declare(strict_types=1);

// Minimal bootstrap for installer only.
// Loads config + autoloader + DB connection. No session, no redirects.

require_once __DIR__ . '/../../../config/config.php';

spl_autoload_register(function (string $class): void {
    $file = __DIR__ . '/../../../App/' . str_replace('\\', '/', $class) . '.php';
    if (is_file($file)) {
        require_once $file;
    }
});

use Database\PDO;

try {
    $db = new PDO('sqlite:' . DB_PATH);

    // Critical: ensure errors throw exceptions
    $db->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
} catch (Throwable $e) {
    http_response_code(500);
    exit('Database connection failed: ' . $e->getMessage());
}

$db->exec('PRAGMA journal_mode = WAL;');
$db->exec('PRAGMA foreign_keys = ON;');
$db->exec('PRAGMA synchronous = NORMAL;');
$db->exec('PRAGMA busy_timeout = 5000;');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(403);
    exit;
}

$action = $_POST['action'] ?? '';

/**
 * Applies all pending SQL migrations from SQL_UPDATES.
 *
 * @param \PDO $db
 * @return array{applied: int, messages: array<int, string>}
 * @throws \Throwable
 */
function applyMigrations(\PDO $db): array
{
    $messages = [];

    // Ensure migrations table exists
    $db->exec("
    CREATE TABLE IF NOT EXISTS db_migrations (
      version TEXT PRIMARY KEY,
      applied_at TEXT NOT NULL
    )
  ");

    // Already applied
    $applied = $db->query("SELECT version FROM db_migrations")
        ->fetchAll(\PDO::FETCH_COLUMN);

    $applied = array_flip($applied ?: []);

    $files = glob(SQL_UPDATES . '/*.sql') ?: [];
    sort($files, SORT_NATURAL);

    $count = 0;

    if (!$files) {
        $messages[] = "No updates found";
        return ['applied' => 0, 'messages' => $messages];
    }

    foreach ($files as $file) {
        $version = basename($file, '.sql');

        if (isset($applied[$version])) {
            continue;
        }

        $messages[] = "Applying {$version}...";

        $sql = file_get_contents($file);
        if ($sql === false || trim($sql) === '') {
            throw new Exception("Empty migration: {$version}");
        }

        $db->exec($sql);

        $stmt = $db->prepare("
      INSERT INTO db_migrations (version, applied_at)
      VALUES (?, datetime('now'))
    ");
        $stmt->execute([$version]);

        $messages[] = "{$version} OK";
        $count++;
    }

    return ['applied' => $count, 'messages' => $messages];
}

/* -------------------------------------------------
   WRITE PASSWORD (config.local.php)
------------------------------------------------- */
if ($action === 'password') {
    $pass = $_POST['password'] ?? '';
    $hash = password_hash($pass, PASSWORD_DEFAULT);

    $file = __DIR__ . '/../../../config/config.local.php';

    $content = <<<PHP
<?php
// AUTO-GENERATED BY INSTALLER

define('APP_PASSWORD_HASH', '{$hash}');
PHP;

    file_put_contents($file, $content, LOCK_EX);
    chmod($file, 0600);

    echo "OK\n";
    exit;
}

/* -------------------------------------------------
   INSTALL + AUTO-UPDATE
------------------------------------------------- */
if ($action === 'install') {
    try {
        $db->beginTransaction();

        $schema = file_get_contents(SQL_SCHEMA);
        if ($schema === false || trim($schema) === '') {
            throw new Exception('schema.sql missing or empty');
        }

        $db->exec($schema);

        // Ensure migrations table exists even if schema.sql didn't include it
        $db->exec("
      CREATE TABLE IF NOT EXISTS db_migrations (
        version TEXT PRIMARY KEY,
        applied_at TEXT NOT NULL
      )
    ");

        // Apply updates immediately (still inside same transaction)
        $result = applyMigrations($db);

        $db->commit();

        // Mark system as installed
        touch(__DIR__ . '/.installed');

        echo "Install complete\n";
        foreach ($result['messages'] as $m) {
            echo $m . "\n";
        }
        echo "Auto-updates applied: {$result['applied']}\n";
    } catch (Throwable $e) {
        if ($db->inTransaction()) {
            $db->rollBack();
        }
        echo "FAILED: {$e->getMessage()}\n";
    }

    exit;
}

/* -------------------------------------------------
   APPLY UPDATES (MIGRATIONS)
------------------------------------------------- */
if ($action === 'update') {
    try {
        $db->beginTransaction();

        $result = applyMigrations($db);

        $db->commit();

        foreach ($result['messages'] as $m) {
            echo $m . "\n";
        }
        echo "Update complete\n";
    } catch (Throwable $e) {
        if ($db->inTransaction()) {
            $db->rollBack();
        }
        echo "UPDATE FAILED: {$e->getMessage()}\n";
    }

    exit;
}

echo "Invalid action\n";
