<?php
// AUTO-GENERATED BY INSTALLER

define('APP_PASSWORD_HASH', '$2y$12$iTnvmzNtfVfdQxcuHBThUOZfsjGCYUCLjuy7NcglOa0lw7TZ3uNMS');

// ================================
// ALERT DEFAULTS
// ================================
define('ALERT_CPU_THRESHOLD', 90);
define('ALERT_RAM_THRESHOLD', 90);
define('ALERT_COOLDOWN', 1800);

define('ALERT_CHANNELS', [
    'discord' => false,
    'email' => false,
    'sms' => false,
    'whatsapp' => false,
]);

define('DISCORD_WEBHOOK_URL', '');
define('ALERT_EMAIL_TO', '');