<?php
declare(strict_types=1);

require_once __DIR__ . '/../../App/Bootstrap.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(403);
    exit;
}

$action = $_POST['action'] ?? '';

/* -------------------------------------------------
   WRITE PASSWORD (config.local.php)
------------------------------------------------- */
if ($action === 'password') {
    $pass = $_POST['password'] ?? '';

    /* if (strlen($pass) < 8) {
        echo "Password too short\n";
        exit;
    } */

    $hash = password_hash($pass, PASSWORD_DEFAULT);

    $file = __DIR__ . '/../../config/config.local.php';

    $content = <<<PHP
<?php
// AUTO-GENERATED BY INSTALLER

define('APP_PASSWORD_HASH', '{$hash}');
PHP;

    file_put_contents($file, $content, LOCK_EX);
    chmod($file, 0600);

    echo "OK\n";
    exit;
}

/* -------------------------------------------------
   INSTALL SCHEMA (FIRST TIME)
------------------------------------------------- */
if ($action === 'install') {
    try {
        $db->beginTransaction();

        $schema = file_get_contents(SQL_SCHEMA);
        if (!$schema) {
            throw new Exception('schema.sql missing');
        }

        $db->exec($schema);

        $db->exec("
            CREATE TABLE IF NOT EXISTS db_migrations (
                version TEXT PRIMARY KEY,
                applied_at TEXT NOT NULL
            )
        ");

        $db->commit();

        // Mark system as installed
        touch(__DIR__ . '/.installed');

        echo "Install complete\n";

    } catch (Throwable $e) {
        $db->rollBack();
        echo "FAILED: {$e->getMessage()}\n";
    }

    exit;
}

/* -------------------------------------------------
   APPLY UPDATES (MIGRATIONS)
------------------------------------------------- */
if ($action === 'update') {
    try {
        $db->beginTransaction();

        // Ensure migrations table exists
        $db->exec("
            CREATE TABLE IF NOT EXISTS db_migrations (
                version TEXT PRIMARY KEY,
                applied_at TEXT NOT NULL
            )
        ");

        // Get already applied migrations
        $applied = $db->query("
            SELECT version FROM db_migrations
        ")->fetchAll(PDO::FETCH_COLUMN);

        $applied = array_flip($applied);

        $files = glob(SQL_UPDATES . '/*.sql');
        sort($files, SORT_NATURAL);

        if (!$files) {
            echo "No updates found\n";
        }

        foreach ($files as $file) {
            $version = basename($file, '.sql');

            if (isset($applied[$version])) {
                continue;
            }

            echo "Applying {$version}...\n";

            $sql = file_get_contents($file);
            if (!$sql) {
                throw new Exception("Empty migration: {$version}");
            }

            $db->exec($sql);

            $stmt = $db->prepare("
                INSERT INTO db_migrations (version, applied_at)
                VALUES (?, datetime('now'))
            ");
            $stmt->execute([$version]);

            echo "{$version} OK\n";
        }

        $db->commit();
        echo "Update complete\n";

    } catch (Throwable $e) {
        $db->rollBack();
        echo "UPDATE FAILED: {$e->getMessage()}\n";
    }

    exit;
}

echo "Invalid action\n";
